name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install server dependencies
      run: npm install
      working-directory: ./server

    - name: Install client dependencies
      run: npm install
      working-directory: ./client

    - name: Run client tests
      run: npm test
      working-directory: ./client

    - name: Run server tests
      run: npm test
      working-directory: ./server

    - name: Build client
      run: npm run build
      working-directory: ./client

    - name: Deploy to Production
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: echo "Deploying to production..."
      # Add your deployment script/command here
